### PR TITLE
Update data generation

### PR DESCRIPTION
**Pull request by lawall4**
* Updates to the data generation script to include more categories of income and expenditure as well as more demographic information such as age band and postal district. 
* Further updates to the data generation script to simulate customers leaving the dataset over time and customers having no transactions in a particular week.
* Updates to the container set up (and hence the Dockerfile) to facilitate the use of one script for generating data both in and out of the container.
* Updated file paths in the hive guide examples to reflect above changes.
* Updated instructions in README to reflect above changes.

### CODE REVIEW

**Comment by mikerspencer** [comment]
# Nitpicks

* Cover provenance of data used, preferably via a download script - this means we don't need to add data to the repo
* Leave a space after `,`, `<`, etc. in code to help readability
* `cut` might be less effort to write that `case_when` for the age_band creation

**Comment by mikerspencer** [comment]
# To review

* Error at end of podman build: `Error: building at STEP "COPY data-output/ data-output/": checking on sources under "/home/mike/repo/hive_guide": copier: stat: "/data-output": no such file or directory`
* All seems to work *but* the tar path no longer matches the `.qmd` example. Can we compress the archive without the directory tree?
* More a comment - I'm not sure it's running in parallel, but this might be a resource constraint on the container? Maybe Jim knows.

**Comment by mikerspencer** [comment]
@lawall4 & @jimgar shall we merge this in now and add Jim's improvements in a separate PR? I'm keen this work is available for Albert.

**Comment by lawall4** [comment]
> @lawall4 & @jimgar shall we merge this in now and add Jim's improvements in a separate PR? I'm keen this work is available for Albert.

Sounds good to me

**Comment by jimgar** [comment]
Sorry folks I didn't see that before pushing my changes up here too.

@lawall4 if you could pull, and make sure the updated instructions in the readme work for you, then it should be good to go.

**Comment by lawall4** [comment]
All working well when running inside the container - also significantly faster than before. When running the standalone R script I get this error: `tar: Couldn't open zstd -T1: No such file or directory` from running this line: `system(sprintf("tar -I 'zstd -T%s' -cvf data-output/test_data.tar.zst data-output/test_data", workers))`. I have double checked that tar and zstd are properly installed so don't think that's the issue.

**Pull request merged**
